name: warn-system
main: letovo.server.warn.Plugin
version: 1.0-SNAPSHOT
api-version: 1.15
authors: ["Penumbrae (aka Doouble1337)"]
description: Allow Vulcan AC to warn players, so that they get banned after 5 cheat detections.
commands:
  warn:
    description: Warn a player
    usage: /warn <player>